# Generated by Django 5.1.4 on 2026-02-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Composante',
                'verbose_name_plural': 'Composantes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('T4', 'Trimestre 4')], max_length=2)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['-annee', '-trimestre'],
                'unique_together': {('annee', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('type_rapport', models.CharField(choices=[('TRIMESTRIEL', 'Rapport Trimestriel'), ('ANNUEL', 'Rapport Annuel'), ('MISSION', 'Rapport de Mission'), ('AUTRE', 'Autre')], max_length=20)),
                ('region', models.CharField(blank=True, choices=[('MARITIME', 'Région Maritime'), ('PLATEAUX', 'Région des Plateaux'), ('CENTRALE', 'Région Centrale'), ('KARA', 'Région de la Kara'), ('SAVANES', 'Région des Savanes'), ('NATIONAL', 'National')], max_length=20)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.periode')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SousComposante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_composantes', to='monitoring.composante')),
            ],
            options={
                'verbose_name': 'Sous-composante',
                'verbose_name_plural': 'Sous-composantes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.TextField()),
                ('type_indicateur', models.CharField(choices=[('QUANTITATIF', 'Quantitatif'), ('QUALITATIF', 'Qualitatif')], max_length=20)),
                ('niveau', models.CharField(choices=[('IMPACT', 'Impact'), ('EFFET', 'Effet'), ('EXTRANT', 'Extrant')], max_length=20)),
                ('unite_mesure', models.CharField(max_length=100)),
                ('valeur_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cible_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_verification', models.TextField(blank=True)),
                ('frequence_collecte', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('sous_composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='monitoring.souscomposante')),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget_execute', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('region', models.CharField(choices=[('MARITIME', 'Région Maritime'), ('PLATEAUX', 'Région des Plateaux'), ('CENTRALE', 'Région Centrale'), ('KARA', 'Région de la Kara'), ('SAVANES', 'Région des Savanes'), ('NATIONAL', 'National')], max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_responsable', to=settings.AUTH_USER_MODEL)),
                ('sous_composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='monitoring.souscomposante')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_debut_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('MARITIME', 'Région Maritime'), ('PLATEAUX', 'Région des Plateaux'), ('CENTRALE', 'Région Centrale'), ('KARA', 'Région de la Kara'), ('SAVANES', 'Région des Savanes')], max_length=20)),
                ('valeur_realisee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commentaire', models.TextField(blank=True)),
                ('fichier_justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('valide', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='monitoring.indicateur')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='monitoring.periode')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations_saisies', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-periode__annee', '-periode__trimestre', 'region'],
                'unique_together': {('indicateur', 'periode', 'region')},
            },
        ),
    ]
