# Generated by Django 5.1.4 on 2026-02-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='femmes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Femmes'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='hommes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hommes'),
        ),
        migrations.CreateModel(
            name='AlerteQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('EXCES', '⚠️ Excès (Réalisé > Cible)'), ('NEGATIF', '🔴 Valeur Négative'), ('VIDE', '❓ Donnée Manquante'), ('INCOHERENT', '⚠️ Incohérence Genre')], max_length=20)),
                ('severite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('IMPORTANT', 'Important'), ('MINEUR', 'Mineur')], default='IMPORTANT', max_length=20)),
                ('message', models.TextField()),
                ('resolue', models.BooleanField(default=False)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='monitoring.realisation')),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte Qualité',
                'verbose_name_plural': 'Alertes Qualité',
                'ordering': ['-date_detection'],
            },
        ),
    ]
