# Generated by Django 5.2.11 on 2026-02-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_realisation_femmes_realisation_hommes_alertequalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='sous_composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='monitoring.souscomposante'),
        ),
    ]
